language: node_js

sudo: false

matrix:
  include:
    - node_js: 10
    - node_js: 12

script:
- npm run build
- npm run test-unit-travis || travis_terminate 1
- npm run lint
- npm run check-packages

after_success:
- npm run report-coverage

deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    node: 12
    branch: master
