language: node_js

sudo: false

matrix:
  include:
    - node_js: 10
    - node_js: 12
      before_script:
        - >-
              [ -z "${TRAVIS_TAG}" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]
              && openssl aes-256-cbc -K $encrypted_3058bc69cb40_key -iv $encrypted_3058bc69cb40_iv -in ghost.env.enc -out ghost.env -d
              && openssl aes-256-cbc -K $encrypted_66f264007c0d_key -iv $encrypted_66f264007c0d_iv -in iam_access_groups.env.enc -out iam_access_groups.env -d
              && openssl aes-256-cbc -K $encrypted_94fa7fdf4df9_key -iv $encrypted_94fa7fdf4df9_iv -in global_catalog.env.enc -out global_catalog.env -d
              && openssl aes-256-cbc -K $encrypted_a72454cfb42f_key -iv $encrypted_a72454cfb42f_iv -in iam_policy_management.env.enc -out iam_policy_management.env -d
              && openssl aes-256-cbc -K $encrypted_6eaa1fc94541_key -iv $encrypted_6eaa1fc94541_iv -in catalog_mgmt.env.enc -out catalog_mgmt.env -d
              || true

#             && openssl aes-256-cbc -K $encrypted_dac53b985913_key -iv $encrypted_dac53b985913_iv -in case_management.env.enc -out case_management.env -d
#             && openssl aes-256-cbc -K $encrypted_acd9ca9788e3_key -iv $encrypted_acd9ca9788e3_iv -in resource_manager.env.enc -out resource_manager.env -d
#             && openssl aes-256-cbc -K $encrypted_25d847003bcf_key -iv $encrypted_25d847003bcf_iv -in enterprise-management.env.enc -out enterprise-management.env -d

script:
- npm run build
- npm run test-travis || travis_terminate 1
- npm run lint
- npm run check-packages
# - sh scripts/typedoc/generate_typedoc.sh

after_success:
- npm run report-coverage
# - scripts/jsdoc/publish.sh

deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    node: 12
    branch: master
